# Application
spring.application.name=backend

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_booking
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true